---
    - name: Update User on systemd file
      lineinfile:
        path: /sn-platform-pulsar/lib/systemd/system/pulsar-manager.service
        regexp: '^User=pulsar-manager'
        line: User=pulsar
      register: systemd_update

    - name: Update ExecStart on systemd file
      lineinfile:
        path: /sn-platform-pulsar/lib/systemd/system/pulsar-manager.service
        regexp: '^ExecStart=/bin/pulsar-manager'
        line: ExecStart=/sn-platform-pulsar/bin/pulsar-manager --redirect.host=http://localhost --redirect.port=9527 insert.stats.interval=600000
      register: systemd_update

    - name: Add WorkingDirectory to systemd file
      lineinfile:
        path: /sn-platform-pulsar/lib/systemd/system/pulsar-manager.service
        insertafter: '^Group=streamnative'
        line: WorkingDirectory=/sn-platform-pulsar/bin
      register: systemd_update

    - name: Create a symbolic link
      file:
        src: /sn-platform-pulsar/lib/systemd/system/pulsar-manager.service
        dest: /etc/systemd/system/pulsar-manager.service
        state: link
      register: systemd_update

    - name: Restart service manager, also issue daemon-reload to pick up config changes
      systemd:
        name: pulsar-manager
        state: restarted
        daemon_reload: yes
      when: systemd_update.changed

    - name: Ensure manager is running
      systemd:
        name: pulsar-manager
        state: started
        enabled: true
        daemon_reload: yes
