---
    - name: Zookeeper restart
      hosts: all
      gather_facts: false
    
      tasks:
        - name: Zookeeper restart
          systemd:
            name: zookeeper
            state: stopped
          when: "'zookeeper' in group_names"
        
        - name: BookKeeper start
          systemd:
            name: bookkeeper
            state: stopped
          when: "'bookkeeper' in group_names"
        
        - name: Broker start
          systemd:
            name: pulsar-broker
            state: stopped
          when: "'broker' in group_names"
