---
    - name: Services start
      hosts: all
      gather_facts: false
    
      tasks:
        - name: Zookeeper start
          systemd:
            name: zookeeper
            state: started
          when: "'zookeeper' in group_names"
        
        - name: BookKeeper start
          systemd:
            name: bookkeeper
            state: started
          when: "'bookkeeper' in group_names"
        
        - name: Broker start
          systemd:
            name: pulsar-broker
            state: started
          when: "'broker' in group_names"
