---
    - name: Services stop
      hosts: all
      gather_facts: false
    
      tasks:
        - name: Zookeeper stop
          systemd:
            name: zookeeper
            state: stopped
          when: "'zookeeper' in group_names"
        
        - name: BookKeeper stop
          systemd:
            name: bookkeeper
            state: stopped
          when: "'bookkeeper' in group_names"
        
        - name: Broker stop
          systemd:
            name: pulsar-broker
            state: stopped
          when: "'broker' in group_names"
